### ISSUE TITLE
Ability to create variables to use in commands

### ISSUE THREAD

**Issue by robwilde** [DannyBen/opcode#19]
First, big thanks to awesome tool. 

I have been using Alf for a while, which is also awesome, and wanted to use opcode for a project that is shared.

Would it be difficult to add similar function from Alf where you can use commands in commands?
As an idea, being able to create a command that starts with `$` so I can call that from another command. like...

```
$dbash: docker compose exec web_local bash -c

php-info: $dbash "php -i"
php-version: $dbash "php -v"
php-modules: $dbash "php -m"
```
thanks again :)

**Comment by DannyBen** [comment]
Both an alf an opcode user, nice! Happy you find them useful.

How about this:

```bash
# op.conf
display1: echo "--- $@"
display2: echo 

greet1: op display1 Hello World
greet2: op display2 Hello "$1", and welcome!
```

then we can run:

```bash
$ op greet1
--- Hello World

$ op greet1 Bob
--- Hello World Bob

$ op greet2 Bob
Hello Bob, and welcome!
```

Not sufficient?

**Comment by robwilde** [comment]
That is actually a format I tried to use, thinking along the lines of Alf.
If that could work in opcode that would work very well.

I would have worked on the solution myself but bash scripting, I am sorry to say, is something on my list of languages to learn.

Thanks again :)

**Comment by DannyBen** [comment]
I think you misunderstood me. This is already implemented in opcode right now.

**Comment by robwilde** [comment]
Oh OK I will try that again. I didn't think that was working but most likely something I did.

**Comment by robwilde** [comment]
Did some more testing and it does not appear to work with docker compose commands.

testing using command to get php version from container
`php-version: docker compose exec dms_web_local bash -c "php -v"`

create a command for docker compose part like so:
`dbshrc: docker compose exec dms_web_local bash -c`

shorten command:
`php-version: dbshrc "php -v"`

returns: `/usr/local/bin/op: line 89: dbshrc: command not found`

Doing this in Alf I use $* in a few places to allow for multiple inputs, seems to work pretty well their

I found that what works is 
`dbshrc: docker compose exec dms_web_local bash -c "$*"`
`php-v: op dbshrc php -v`

thought I would share what I found. thanks again for your help
