### ISSUE TITLE
Improve opcode help?

### ISSUE THREAD

**Issue by niksfirefly** [DannyBen/opcode#24]
I wonder is it possible todo:

1.hide duplicate commands that i choose from 
`op ?`
I put commands with aliases in op.conf
```
debug: ..
deb: op debug
deploy: ..
dep: op deploy
```
and I want to see only choosen commands with description `#? .... ` - for example aliases to unclutter log commands list

2.Is there a way to remove from
`op -s`
comments
`#? .... `

I think `op -s` should contain full command list without help contrary to `op ?`

regards

**Comment by DannyBen** [comment]
You do not need to create aliases.

As mentioned in the README and discovered in the previous ticket, partial matches work automatically.

If you have a `deploy` command, you can run it with `d`, `de`, `dep` and anything up to `deploy`.

As for `op -s`, it is unlikely to change its behavior, but I will consider it.

**Comment by DannyBen** [comment]
Also there is the [autocomplete](https://github.com/DannyBen/opcode#bash-completion), so between this and the partial matching - there should be no reason to write duplicate commands.

**Comment by DannyBen** [comment]
I am going to make it so `op -w` will work also without getting a command code, and in this case, it will show all code and their command.

**Comment by DannyBen** [comment]
You can try version 0.6.2, and run `op -w` to see all code:command pairs.

**Comment by niksfirefly** [comment]
This is great! Very nice thank you

I disagree about aliases because in real life there could be aliases like that
```
enable: ...
on: alias...
```
Generally option to remove some commands from op -w / op -s could be useful
but i can live with that
regards

**Comment by DannyBen** [comment]
Would you expect these hidden commands to be displayed when you just run `op` without arguments?

**Comment by niksfirefly** [comment]
I think that's a no
I think I am abusing your time
Thank you anyway for good work

**Comment by DannyBen** [comment]
I may be adding private commands, need to think about it.
In any case, it is tracked in #27
