### ISSUE TITLE
Allow private codes

### ISSUE THREAD

**Issue by DannyBen** [DannyBen/opcode#27]
Consider adding an ability to mark an opcode "private", so that it is not shown in any of the listing commands.

Possible use cases:

1. Aliases (brought up in #24)
2. Internal opcodes

**Comment by DannyBen** [comment]
@niksfirefly - how about using a syntax like this?
Anything below the keyword `private` will not be visible anywhere other than `op -s`.

```bash
one: echo one
#? one

two: op three
#? two and three

private

three: echo two and three
```

**Comment by niksfirefly** [comment]
Clean, excellent solution!
